### ISSUE TITLE
Game Item parsing broken

### ISSUE THREAD

**Issue by jokerServer** [xKynn/PoE.py#2]
The parsing for game items `parse_pob_item` is currently broken. 
I'm sadly not that great at Python or else I wouldve reworked the item parsing as a whole.

From what I observed there are only 2 groups of lines that are not especially pre- or suffixed (which are explicit mods and flavor text) and those two you can differenciate with order of occurence. 

Examples that are not working:
```
Rarity: Unique
Carcass Jack
Varnished Coat
--------
Quality: +20% (augmented)
Evasion Rating: 960 (augmented)
Energy Shield: 186 (augmented)
--------
Requirements:
Level: 68
Dex: 108
Int: 151
--------
Sockets: G-B-B-G-B-B 
--------
Item Level: 79
--------
128% increased Evasion and Energy Shield
+65 to maximum Life
+12% to all Elemental Resistances
41% increased Area of Effect
45% increased Area Damage
Extra gore
--------
"...The discomfort shown by the others is amusing, but none
can deny that my work has made quite the splash..."
- Maligaro's Journal
```

```
Rarity: Unique
Doryani's Prototype
Saint's Hauberk
--------
Armour: 1267 (augmented)
Energy Shield: 209 (augmented)
--------
Requirements:
Level: 67
Str: 109
Int: 94
--------
Sockets: R-B R 
--------
Item Level: 78
--------
186% increased Armour and Energy Shield
+79 to maximum Life
Deal no Non-Lightning Damage
Armour also applies to Lightning Damage taken from Hits
Lightning Resistance does not affect Lightning Damage taken
Nearby Enemies have Lightning Resistance equal to yours
--------
"This was the first step in some grand design, 
lost to the ages, now ours to decipher." 
- Dominus, High Templar```

**Comment by xKynn** [comment]
Hey, thanks for your report, `parse_pob_item` has been really messy for a bit It's up there with a few things for a rewrite soon.

**Comment by jokerServer** [comment]
With recent updates, now most of the base items should be parseable
apart from not rollable items like currency, gems, etc

an important part that is still missing is cluster jewel support
as far as I can see the parse_game_item() correctly parses the mods?

**Comment by xKynn** [comment]
Fixed in https://github.com/xKynn/PoE.py/commit/ce453d16be9ea49b54f83ad6664638b16a16cd96 and https://github.com/xKynn/PoE.py/commit/98b6182611c1e371efc4e735a289c73aaeefe825.

Tracking cluster jewel support at https://github.com/xKynn/PoE.py/issues/5

**Comment by Shocky92** [comment]
It's broken again. Zana can generate items through brackets (ex. [[Headhunter]]). But from copypaste it's not working.

![изображение](https://user-images.githubusercontent.com/9486962/115418795-95719e00-a21b-11eb-92ed-9118d7426ff1.png)
![изображение](https://user-images.githubusercontent.com/9486962/115418886-b0441280-a21b-11eb-8f2e-90d8c423e9db.png)

**Comment by xKynn** [comment]
Thanks for your report. This has a very simple fix I will be pushing out soon it is just related to the new text now starting with Item Class instead of Rarity

**Comment by xKynn** [comment]
Fixed in https://github.com/xKynn/zana/commit/80ccdb44528519bc67b4418ed468ae9f2665dadc & https://github.com/xKynn/PoE.py/commit/29ceb6bb593e1d2624bba76de05fd8275f551315.
